name: Comment on PR Closure

on:
  pull_request_target:
    types:
      - closed

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR Merge Status
        id: pr_status
        run: echo "::set-output name=merged::${{ github.event.pull_request.merged }}"

      - name: Comment on PR Closure
        if: steps.pr_status.outputs.merged == 'true'
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo, number } = context.issue;
            const commentAuthor = context.payload.pull_request.user.login;
            const commentBody = `Hey @${ commentAuthor } 🎉 Your pull request has been successfully merged! 🎉 Thank you for your valuable contribution to our project. Your efforts are greatly appreciated. Feel free to reach out if you have any more contributions or if there's anything else we can assist you with. Keep up the fantastic work! 🚀`;
            await github.issues.createComment({ owner, repo, issue_number: number, body: commentBody });
            console.log(`Commented on the closed PR: ${commentBody}.`);
        
      - name: Comment on PR Closure
        if: steps.pr_status.outputs.merged != 'true'
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo, number } = context.issue;
            const commentAuthor = context.payload.pull_request.user.login;
            const commentBody = `Hey @${ commentAuthor } ,Wanted to let you know that we have decided to close your pull request.
            In case of any issues, you can contact us.
            Thank you!`;
            await github.issues.createComment({ owner, repo, issue_number: number, body: commentBody });
            console.log(`Commented on the closed PR: ${commentBody}.`);
